template_path: templates/vpc.stack.yaml

hooks:
  before_create: 
    - !cmd "echo creating VPC"

parameters:
  VpcBlock: 192.168.0.0/16

  Subnet01Block: 192.168.64.0/18

  Subnet02Block: 192.168.128.0/18

  Subnet03Block: 192.168.192.0/18
